#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-2"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "514042d6a10f4d5dbd9a9168eb43cb50" }
]

[assets]
directory = "./public"
